### PR TITLE
On appear issue

### PR DESCRIPTION
**Pull request by eddieredmann3**
Hayley, the onAppear function is necessary apparently, but we're not making a new recorder every time we open the page.

### CODE REVIEW

**Review by HayleyO — APPROVED** [review]

**Comment by HayleyO** [comment]
Don't merge until hardware tested (and on simulator)

**Review by tdog989 — CHANGES_REQUESTED** [review]
The line of code "recordModel.setup()" needs to be put back in so that recording works on the watch. Without this line, it will not function.

**Comment by tdog989** [comment]
[Fix on Appear Create Record](https://trello.com/c/aB0EUtS4/168-fix-on-appear-create-record)

**Comment by eddieredmann3** [comment]
I've re-entered the line, so I think it's ready to merge.

**Review by tdog989 — APPROVED** [review]
Code looks good and worked on hardware!

**Pull request merged**
